### ISSUE TITLE
Smart Contract Scan Queue shows expired scans again when a new entry comes in.

### ISSUE THREAD

**Issue by bbruijn** [quantstamp/qsp-protocol-node#487] opened 2019-06-04 18:03 UTC
## Expected Behavior

The Smart Contract Scan Queue clears after a while (not sure how long expired scan stay visible)

## Current Behavior

Today I noticed that the Smart Contract Scan Queue was empty but when a new scan request expired, it also showed an earlier expired scan request again. 
![Schermafbeelding 2019-06-04 om 19 58 28](https://user-images.githubusercontent.com/11259481/58902355-3710a480-8703-11e9-9fee-ec27f232c702.png)

## Possible Solution

Not sure how the filter for this section is set up, the scan request comes from the same address as the earlier expired request.
Maybe this is intended behavior?

## Your Environment

* Version of this software:
* Operating System and version:

**Comment by alex-murashkin** [comment] 2019-06-04 18:17
Good catch, this looks like a bug. I will open a ticket in the Protocol UI maintenance board. The expected behaviour is that the expired scans aren't visible in the Scan Queue UI.

**Comment by alex-murashkin** [comment] 2019-06-11 13:16
This should be fixed by now. The changes have been promoted to production. If you still can reproduce the issue, please feel free to re-open the issue!

**Closed by alex-murashkin** 2019-06-11 13:16 UTC
