### ISSUE TITLE
[BUG]Mac mismatch wile running node 

### ISSUE THREAD

**Issue by BravoNyN** [quantstamp/qsp-protocol-node#492] opened 2019-06-06 23:43 UTC
Json file mac mismatch error while running node 
Keystore file copied to default.json 

## Current Behavior
Mac mismatch node wont start but keeps calling for json file 

## Error message from node 

Loaded image: qsp-protocol-node:latest
b61189bb2b06aa5592db5effa552bf0d0758780625b1960ac774b596290861b9
{"message": "Connected on attempt 0", "threadName": "MainThread", "lineno": 118, "pathname": "/app/src/qsp_protocol_node/config/config_utils.py", "logger": "ConfigUtils", "level": "debug", "timestamp": "2019-06-06T23:33:27.701092Z"}
{"message": "Error in running node: Error reading or decrypting the keystore file './resources/keystore/default.json': MAC mismatch", "threadName": "MainThread", "lineno": 195, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "error", "timestamp": "2019-06-06T23:33:28.051614Z", "exception": "Traceback (most recent call last):\n  File \"/app/src/qsp_protocol_node/config/config_utils.py\", line 146, in create_web3_client\n    new_private_key = web3_client.eth.account.decrypt(encrypted_key, account_passwd)\n  File \"/usr/lib/python3.6/site-packages/eth_account/account.py\", line 127, in decrypt\n    return decode_keyfile_json(keyfile, password_bytes)\n  File \"/usr/lib/python3.6/site-packages/eth_keyfile/keyfile.py\", line 49, in decode_keyfile_json\n    return _decode_keyfile_json_v3(keyfile_json, password)\n  File \"/usr/lib/python3.6/site-packages/eth_keyfile/keyfile.py\", line 170, in _decode_keyfile_json_v3\n    raise ValueError(\"MAC mismatch\")\nValueError: MAC mismatch\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 191, in <module>\n    Program.run(os.environ['QSP_ETH_PASSPHRASE'], os.environ['QSP_ETH_AUTH_TOKEN'], sol_file)\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 138, in run\n    auth_token=eth_auth_token,\n  File \"/app/src/qsp_protocol_node/config/config_factory.py\", line 32, in create_from_dictionary\n    auth_token, validate_contract_settings)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 196, in load_dictionary\n    self.__create_components(config_utils, validate_contract_settings)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 169, in __create_components\n    config_utils)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 148, in __create_web3_client\n    self.account_keystore_file,\n  File \"/app/src/qsp_protocol_node/config/config_utils.py\", line 152, in create_web3_client\n    exception)\nconfig.config_utils.ConfigurationException: Error reading or decrypting the keystore file './resources/keystore/default.json': MAC mismatch"}
{"message": "Connected on attempt 0", "threadName": "MainThread", "lineno": 118, "pathname": "/app/src/qsp_protocol_node/config/config_utils.py", "logger": "ConfigUtils", "level": "debug", "timestamp": "2019-06-06T23:33:59.270239Z"}
{"message": "Error in running node: Error reading or decrypting the keystore file './resources/keystore/default.json': MAC mismatch", "threadName": "MainThread", "lineno": 195, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "error", "timestamp": "2019-06-06T23:33:59.630583Z", "exception": "Traceback (most recent call last):\n  File \"/app/src/qsp_protocol_node/config/config_utils.py\", line 146, in create_web3_client\n    new_private_key = web3_client.eth.account.decrypt(encrypted_key, account_passwd)\n  File \"/usr/lib/python3.6/site-packages/eth_account/account.py\", line 127, in decrypt\n    return decode_keyfile_json(keyfile, password_bytes)\n  File \"/usr/lib/python3.6/site-packages/eth_keyfile/keyfile.py\", line 49, in decode_keyfile_json\n    return _decode_keyfile_json_v3(keyfile_json, password)\n  File \"/usr/lib/python3.6/site-packages/eth_keyfile/keyfile.py\", line 170, in _decode_keyfile_json_v3\n    raise ValueError(\"MAC mismatch\")\nValueError: MAC mismatch\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 191, in <module>\n    Program.run(os.environ['QSP_ETH_PASSPHRASE'], os.environ['QSP_ETH_AUTH_TOKEN'], sol_file)\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 138, in run\n    auth_token=eth_auth_token,\n  File \"/app/src/qsp_protocol_node/config/config_factory.py\", line 32, in create_from_dictionary\n    auth_token, validate_contract_settings)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 196, in load_dictionary\n    self.__create_components(config_utils, validate_contract_settings)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 169, in __create_components\n    config_utils)\n  File \"/app/src/qsp_protocol_node/config/config.py\", line 148, in __create_web3_client\n    self.account_keystore_file,\n  File \"/app/src/qsp_protocol_node/config/config_utils.py\", line 152, in create_web3_client\n    exception)\nconfig.config_utils.ConfigurationException: Error reading or decrypting the keystore file './resources/keystore/default.json': MAC mismatch"}

**Comment by lpassos** [comment] 2019-06-06 23:48
Hi @BravoNyN ,

Did you execute this particular step stated in the [manual](https://github.com/quantstamp/qsp-protocol-node)?

```
4. Replace the contents of default keystore json file in resources/keystore directory with a valid keystore file.
```

**Comment by BravoNyN** [comment] 2019-06-06 23:48
yes i did

**Comment by arshdeeptinna** [comment] 2019-06-07 00:42
Hi @BravoNyN 

Can you install [eth_keyfile](https://github.com/ethereum/eth-keyfile) and try decrypting the file locally using something like just to understand if the issue is related to keystore file or  the node
```
import eth_keyfile
f = eth_keyfile.load_keyfile('<file-path>')
eth_keyfile.decode_keyfile_json(f, 'password')
```

**Comment by martinetlee** [comment] 2019-06-07 01:33
Adding some context here, I asked BravoNyn to try a couple of things and it seemed to be normal:
1. He was able to use the keystore file and his passphrase on MEW to show his account
2. He had confirmed that he was running it in the node directory
3. the keystore file was directly copied into the correct location
4. QSP_ETH_PASSPHRASE was correctly set, as he unlocked the MEW with what was printed with the echo $QSP_ETH_PASSPHRASE

He was suspecting that would it possibly be the environment issue (Ubuntu 18.04.2 LTS Bionic Beaver) as he had problem with it earlier when running docker.

**Comment by alex-murashkin** [comment] 2019-06-07 01:47
Could it be the case that the value gets distorted when passed into Docker? https://github.com/quantstamp/qsp-protocol-node/blob/develop/bin/start-node#L71 uses double-quotes, what if try replacing it with single ones in `bin/start-node`?

Also, in `bin/start-node`, can you try temporarily replacing `qsp-protocol-node sh -c "./bin/qsp-protocol-node -a $QSP_ENV $QSP_CONFIG"` with `qsp-protocol-node sh` to run a container without running the node start command and then, inside the container, doing `echo $QSP_ETH_PASSPHRASE`?

**Comment by BravoNyN** [comment] 2019-06-07 11:05
i believe i fixed it 
When i was echo-ing my passphrase i noticed it had 'Passphrase' as echo return .. so with the ' 
it turned out the ' was different and was added to the passphrase itself .. i don't know why but it happened
i copy the ' from the Auth token command .. and that fixed it

**Comment by BravoNyN** [comment] 2019-06-07 11:19
' was ’ ..on export QSP_ETH_PASSPHRASE='*****' .. slightly difference but that made the passphrase think the ' was part of the passphrase that's why the MAC mismatch happened

**Comment by martinetlee** [comment] 2019-06-07 13:58
I checked that our node operator manual seems to have ' instead of `, nevertheless, it might be possible that browsers did that transformation. I'll add a small section to the node-operator manual so that it is clear that they shouldn't be seeing stuff other than their passphrase when users echo the environment variable. 

Closing this!

**Closed by martinetlee** 2019-06-07 13:58 UTC
